export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";
export const USER_ERROR = "USER_ERROR";

export const GET_DEVICES = "GET_DEVICES";
export const GET_USERNAMELIST = "GET_USERNAMELIST";
export const DEVICES_ERROR = "DEVICES_ERROR";
export const GET_USERTOKEN = "GET_USERTOKEN";
export const GET_TOKENERROR = "GET_USERTOKEN";
export const GET_USERS = "GET_USERS";

export const SWITCH_MENU_VISIBLE = "SWITCH_MENU_VISIBLE";
export const SWITCH_SIDEBAR_VISIBLE = "SWITCH_SIDEBAR_VISIBLE";
export const TOGGLE_MAP_MODE = "TOGGLE_MAP_MODE";
